# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenmlops

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenappmlops.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1a32fbbe069a4104b726b661d1c4d573 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_304bacfbc23a407392233fee21f67704 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenappmlops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1a32fbbe069a4104b726b661d1c4d573 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenmlops'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ea1d1a85d69e4c479ed59eba3667b4ed }}
        images: 'chickenappmlops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1a32fbbe069a4104b726b661d1c4d573 }}/chicken:${{ github.sha }}'